# app base image

FROM node:16

ARG APP_DIR
ARG APP_NAME

ENV _APP_DIR=$APP_DIR
ENV _APP_NAME=$APP_NAME

WORKDIR /usr/src/accounts

COPY . .

RUN node ./common/scripts/install-run-rush.js update
RUN node ./common/scripts/install-run-rush.js gen
RUN node ./common/scripts/install-run-rush.js build --to-except $APP_NAME

EXPOSE 3000 3001 4000 24678

CMD cd "/usr/src/accounts/apps/$_APP_DIR" && node /usr/src/accounts/common/scripts/install-run-rushx.js dev