FROM node:16-buster

WORKDIR /usr/src/accounts

COPY ./ ./

RUN node ./common/scripts/install-run-rush.js update
RUN node ./common/scripts/install-run-rush.js gen
RUN node ./common/scripts/install-run-rush.js build --to-except @dritelabs/accounts-frontend

ENV HOST 0.0.0.0
ENV PORT 8000
ENV NODE_ENV development

CMD [ "node", "/usr/src/accounts/common/scripts/install-run-rush.js", "dev", "--only", "@dritelabs/accounts-frontend", "-v"]