{{- include "accounts.secret" (list . "accounts-frontend.secret") -}}
{{- define "accounts-frontend.secret" -}}
data:
  S3_ACCESS_KEY_ID: {{ "LEDXE36FJGJZOJQZEN2E" | b64enc }}
  S3_SECRET_ACCESS_KEY: {{ "kFY2Zj2wxjjAz2th87Id+C+sEwVed46NzQHs04sT4IY" | b64enc }}
{{- end -}}