/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./graphql/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSON";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    jsonObject<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSONObject";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSON";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    jsonObject<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSONObject";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AddJWKToClientInput: { // input type
    clientId: string; // String!
    jwk: NexusGenScalars['JSONObject']; // JSONObject!
  }
  CreateClientInput: { // input type
    description: string; // String!
    name: string; // String!
    type: string; // String!
  }
  UpdateClientInput: { // input type
    contacts?: Array<string | null> | null; // [String]
    description?: string | null; // String
    grantTypes?: Array<string | null> | null; // [String]
    id: string; // String!
    jwksUri?: string | null; // String
    logoUri?: string | null; // String
    name?: string | null; // String
    policyUri?: string | null; // String
    publicKeysConfiguration?: string | null; // String
    redirectUris?: Array<string | null> | null; // [String]
    refreshTokenRotationType?: string | null; // String
    responseTypes?: Array<string | null> | null; // [String]
    softwareId?: string | null; // String
    softwareVersion?: string | null; // String
    tokenEndpointAuthMethod?: string | null; // String
    tosUri?: string | null; // String
    uri?: string | null; // String
  }
  UpdateClientSecretInput: { // input type
    id: string; // String!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  JSON: any
  JSONObject: any
}

export interface NexusGenObjects {
  Client: { // root type
    contacts?: Array<string | null> | null; // [String]
    createdAt?: string | null; // String
    description?: string | null; // String
    grantTypes?: Array<string | null> | null; // [String]
    id?: string | null; // String
    isFirstParty?: boolean | null; // Boolean
    jwks?: NexusGenScalars['JSONObject'] | null; // JSONObject
    jwksUri?: string | null; // String
    logoUri?: string | null; // String
    name?: string | null; // String
    policyUri?: string | null; // String
    publicKeysConfiguration?: string | null; // String
    redirectUris?: Array<string | null> | null; // [String]
    refreshTokenRotationType?: string | null; // String
    responseTypes?: Array<string | null> | null; // [String]
    scope?: string | null; // String
    secret?: string | null; // String
    softwareId?: string | null; // String
    softwareVersion?: string | null; // String
    tokenEndpointAuthMethod?: string | null; // String
    tosUri?: string | null; // String
    type?: string | null; // String
    updatedAt?: string | null; // String
    uri?: string | null; // String
    userId?: string | null; // String
  }
  JWKPair: { // root type
    privateKey?: NexusGenScalars['JSONObject'] | null; // JSONObject
    publicKey?: NexusGenScalars['JSONObject'] | null; // JSONObject
  }
  Mutation: {};
  Query: {};
  Viewer: { // root type
    email?: string | null; // String
    firstName?: string | null; // String
    id?: string | null; // String
    lastName?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Client: { // field return type
    contacts: Array<string | null> | null; // [String]
    createdAt: string | null; // String
    description: string | null; // String
    grantTypes: Array<string | null> | null; // [String]
    id: string | null; // String
    isFirstParty: boolean | null; // Boolean
    jwks: NexusGenScalars['JSONObject'] | null; // JSONObject
    jwksUri: string | null; // String
    logoUri: string | null; // String
    name: string | null; // String
    policyUri: string | null; // String
    publicKeysConfiguration: string | null; // String
    redirectUris: Array<string | null> | null; // [String]
    refreshTokenRotationType: string | null; // String
    responseTypes: Array<string | null> | null; // [String]
    scope: string | null; // String
    secret: string | null; // String
    softwareId: string | null; // String
    softwareVersion: string | null; // String
    tokenEndpointAuthMethod: string | null; // String
    tosUri: string | null; // String
    type: string | null; // String
    updatedAt: string | null; // String
    uri: string | null; // String
    userId: string | null; // String
  }
  JWKPair: { // field return type
    privateKey: NexusGenScalars['JSONObject'] | null; // JSONObject
    publicKey: NexusGenScalars['JSONObject'] | null; // JSONObject
  }
  Mutation: { // field return type
    addJWKToClient: NexusGenRootTypes['Client'] | null; // Client
    createClient: NexusGenRootTypes['Client'] | null; // Client
    createJWKPair: NexusGenRootTypes['JWKPair'] | null; // JWKPair
    deleteClient: NexusGenRootTypes['Client'] | null; // Client
    updateClient: NexusGenRootTypes['Client'] | null; // Client
    updateClientSecret: NexusGenRootTypes['Client'] | null; // Client
  }
  Query: { // field return type
    client: NexusGenRootTypes['Client'] | null; // Client
    clients: Array<NexusGenRootTypes['Client'] | null>; // [Client]!
    viewer: NexusGenRootTypes['Viewer'] | null; // Viewer
  }
  Viewer: { // field return type
    email: string | null; // String
    firstName: string | null; // String
    id: string | null; // String
    lastName: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Client: { // field return type name
    contacts: 'String'
    createdAt: 'String'
    description: 'String'
    grantTypes: 'String'
    id: 'String'
    isFirstParty: 'Boolean'
    jwks: 'JSONObject'
    jwksUri: 'String'
    logoUri: 'String'
    name: 'String'
    policyUri: 'String'
    publicKeysConfiguration: 'String'
    redirectUris: 'String'
    refreshTokenRotationType: 'String'
    responseTypes: 'String'
    scope: 'String'
    secret: 'String'
    softwareId: 'String'
    softwareVersion: 'String'
    tokenEndpointAuthMethod: 'String'
    tosUri: 'String'
    type: 'String'
    updatedAt: 'String'
    uri: 'String'
    userId: 'String'
  }
  JWKPair: { // field return type name
    privateKey: 'JSONObject'
    publicKey: 'JSONObject'
  }
  Mutation: { // field return type name
    addJWKToClient: 'Client'
    createClient: 'Client'
    createJWKPair: 'JWKPair'
    deleteClient: 'Client'
    updateClient: 'Client'
    updateClientSecret: 'Client'
  }
  Query: { // field return type name
    client: 'Client'
    clients: 'Client'
    viewer: 'Viewer'
  }
  Viewer: { // field return type name
    email: 'String'
    firstName: 'String'
    id: 'String'
    lastName: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addJWKToClient: { // args
      input?: NexusGenInputs['AddJWKToClientInput'] | null; // AddJWKToClientInput
    }
    createClient: { // args
      input?: NexusGenInputs['CreateClientInput'] | null; // CreateClientInput
    }
    deleteClient: { // args
      id?: string | null; // String
    }
    updateClient: { // args
      input?: NexusGenInputs['UpdateClientInput'] | null; // UpdateClientInput
    }
    updateClientSecret: { // args
      input?: NexusGenInputs['UpdateClientSecretInput'] | null; // UpdateClientSecretInput
    }
  }
  Query: {
    client: { // args
      id?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}